# =================================================================
# CONFIGURAZIONE GENERALE
# =================================================================
log_dest stderr
log_type error
log_type warning
log_type notice
log_type information
log_type debug
log_type subscribe
log_type unsubscribe

# =================================================================
# LISTENER 1: IN CHIARO (Porta interna 1883) PER NODERED
# =================================================================
listener 1883 0.0.0.0
# Permette le connessioni senza usare certificati o password
listener_allow_anonymous true

# =================================================================
# LISTENER 2: SICURO MQTTS (Porta interna 8883)
# =================================================================
listener 8883 0.0.0.0
# Disabilita l'accesso anonimo su questa porta
listener_allow_anonymous false
# Richiede obbligatoriamente che il client (Arduino) presenti il suo certificato
require_certificate true
# Usa il campo Common Name (CN) del certificato Arduino come username MQTT
use_identity_as_username true

# I CERTIFICATI VANNO SOTTO IL LISTENER 8883:
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key


# =================================================================
# LISTENER 3: SICURO MQTTS (Porta interna 5678) Ma non serve sapere chi si e' tramite certificati
# serve per test
# =================================================================
listener 5678 0.0.0.0
listener_allow_anonymous true  # Entrano tutti liberamente
require_certificate false      # Il client NON deve mostrare il suo certificato
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
